# database generated on 2023-02-28 07:40 GMT
!!omap
- /home/anusha/new/RV32H/fcvt.h.w/test/fcvt.h.w_b25-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fcvt.h.w_b25
- /home/anusha/new/RV32H/fcvt.h.w/test/fcvt.h.w_b26-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fcvt.h.w_b26
