# database generated on 2023-02-28 07:30 GMT
!!omap
- /home/anusha/new/RV32H/fsub/test/fsub_b1-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b1
- /home/anusha/new/RV32H/fsub/test/fsub_b10-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b10
- /home/anusha/new/RV32H/fsub/test/fsub_b11-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b11
- /home/anusha/new/RV32H/fsub/test/fsub_b12-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b12
- /home/anusha/new/RV32H/fsub/test/fsub_b13-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b13
- /home/anusha/new/RV32H/fsub/test/fsub_b2-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b2
- /home/anusha/new/RV32H/fsub/test/fsub_b3-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b3
- /home/anusha/new/RV32H/fsub/test/fsub_b4-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b4
- /home/anusha/new/RV32H/fsub/test/fsub_b5-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b5
- /home/anusha/new/RV32H/fsub/test/fsub_b7-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b7
- /home/anusha/new/RV32H/fsub/test/fsub_b8-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsub_b8
