# database generated on 2023-02-28 07:17 GMT
!!omap
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b1-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b1
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b2-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b2
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b3-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b3
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b4-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b4
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b5-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b5
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b7-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b7
- /home/anusha/new/RV32H/fsqrt/test/fsqrt_b8-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*F.*Zfh.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fsqrt_b8
