# database generated on 2023-02-28 07:22 GMT
!!omap
- /home/anusha/new/RV32H/flh/test/flh-align-01.S:
    commit_id: '-'
    isa:
    - RV32IF_Zicsr_Zfh
    - RV64IF_Zicsr_Zfh
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - flh-align
